#include QMK_KEYBOARD_H
#if __has_include("keymap.h")
#    include "keymap.h"
#endif


/* THIS FILE WAS GENERATED!
 *
 * This file was generated by qmk json2c. You may or may not want to
 * edit it directly.
 */


const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {


    /*
     * ,--------------------------------------------------.    ,--------------------------------------------------.
     * |    0   |   1  |   2  |   3  |   4  |   5  |  6   |    |  38  |  39  |  40  |  41  |  42  |  43  |   44   |
     * |--------+------+------+------+------+------+------|    |------+------+------+------+------+------+--------|
     * |    7   |   8  |   9  |  10  |  11  |  12  |  13  |    |  45  |  46  |  47  |  48  |  49  |  50  |   51   |
     * |--------+------+------+------+------+------|      |    |      |------+------+------+------+------+--------|
     * |   14   |  15  |  16  |  17  |  18  |  19  |------|    |------|  52  |  53  |  54  |  55  |  56  |   57   |
     * |--------+------+------+------+------+------|  26  |    |  58  |------+------+------+------+------+--------|
     * |   20   |  21  |  22  |  23  |  24  |  25  |      |    |      |  59  |  60  |  61  |  62  |  63  |   64   |
     * `--------+------+------+------+------+-------------'    `-------------+------+------+------+------+--------'
     *   |  27  |  28  |  29  |  30  |  31  |                                |  65  |  66  |  67  |  68  |  69  |
     *   `----------------------------------'                                `----------------------------------'
     *                                       ,-------------.  ,-------------.
     *                                       |  32  |  33  |  |  70  |  71  |
     *                                ,------+------+------|  |------+------+------.
     *                                |      |      |  34  |  |  72  |      |      |
     *                                |  35  |  36  |------|  |------|  74  |  75  |
     *                                |      |      |  37  |  |  73  |      |      |
     *                                `--------------------'  `--------------------'
     */

[0] = LAYOUT_ergodox_pretty(
  KC_NO,    KC_1,    KC_2,         KC_3,   KC_4,    KC_5, KC_MINS,      KC_EQL , KC_6   , KC_7   , KC_8   , KC_9  , KC_0   , KC_LBRC,
 KC_TAB,    KC_Q,    KC_W,         KC_E,   KC_R,    KC_T,    KC_5,      KC_ENT , KC_Y   , KC_U   , KC_I   , KC_O  , KC_P   , KC_RBRC,
 KC_ESC,    KC_A,    KC_S,         KC_D,   KC_F,    KC_G,                        KC_H   , KC_J   , KC_K   , KC_L  , KC_SCLN, KC_QUOT,
KC_LSFT,    KC_Z,    KC_X,         KC_C,   KC_V,    KC_B, KC_MINS,      KC_LT  , KC_N   , KC_M   , KC_COMM, KC_DOT, KC_SLSH, KC_NUHS,
KC_LCTL, KC_LGUI, KC_LALT, LSFT(KC_TAB), KC_TAB,                                          KC_LEFT, KC_DOWN, KC_UP , KC_RGHT, KC_NO  ,

                                                  KC_DEL,   KC_NO,      KC_RALT, KC_ENT ,
                                                            TG(3),      KC_NO  ,
                                         KC_SPC, KC_BSPC,   TG(1),      TG(2)  , KC_RCTL, KC_LSFT
),

[1] = LAYOUT_ergodox_pretty(
KC_TRNS,      KC_F1,      KC_F2,      KC_F3,        KC_F4,        KC_F5,         KC_F6,      KC_F7  , KC_F8  , KC_F9  , KC_F10 , KC_F11 , KC_F12    , KC_NO,
KC_TRNS,       KC_8, RALT(KC_0), RALT(KC_4), RALT(KC_EQL),      KC_PPLS,       KC_NUBS,      KC_TRNS, KC_1   , KC_PMNS, KC_PEQL, KC_4   , RALT(KC_6), KC_NO,
KC_TRNS, RALT(KC_3),    KC_RBRC,       KC_5,      KC_MINS,      KC_PAST,                              KC_LEFT, KC_DOWN, KC_UP  , KC_RGHT, RALT(KC_7), KC_NO,
KC_TRNS,    KC_QUOT,    KC_LBRC, RALT(KC_5), RALT(KC_EQL), LSFT(KC_DOT), LSFT(KC_NUBS),      KC_TRNS, KC_SLSH, KC_NO  , KC_NO  , KC_NO  , RALT(KC_8), KC_NO,
KC_TRNS,    KC_TRNS,    KC_TRNS,    KC_TRNS,      KC_TRNS,                                                     KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS   , KC_NO,

                                                                KC_TRNS,       KC_TRNS,      KC_TRNS, KC_TRNS,
                                                                               KC_TRNS,      KC_TRNS,
                                                  KC_TRNS,      KC_TRNS,       KC_TRNS,      KC_TRNS, KC_TRNS, KC_TRNS
),

[2] = LAYOUT_ergodox_pretty(
KC_NO, KC_EXLM, KC_AT, KC_HASH,  KC_DLR, KC_PERC,   KC_NO,      KC_NO  , KC_CIRC, KC_AMPR, KC_ASTR, KC_LPRN, KC_RPRN, KC_NO,
KC_NO,   KC_NO, KC_NO,   KC_NO,   KC_NO,   KC_NO,   KC_NO,      KC_TRNS, KC_NO  , KC_AMPR, KC_ASTR, KC_LPRN, KC_NO  , KC_NO,
KC_NO,   KC_NO, KC_NO,   KC_NO,   KC_NO,   KC_NO,                        KC_NO  , KC_DLR , KC_PERC, KC_CIRC, KC_NO  , KC_NO,
KC_NO,   KC_NO, KC_NO,   KC_NO,   KC_NO,   KC_NO,   KC_NO,      KC_TRNS, KC_NO  , KC_EXLM, KC_AT  , KC_HASH, KC_NO  , KC_NO,
KC_NO,   KC_NO, KC_NO,   KC_NO,   KC_NO,                                          KC_NO  , KC_NO  , KC_RPRN, KC_NO  , KC_NO,

                                         KC_TRNS, KC_TRNS,      KC_TRNS, KC_TRNS,
                                                  KC_TRNS,      KC_TRNS,
                                KC_TRNS, KC_TRNS, KC_TRNS,      KC_TRNS, KC_TRNS, KC_TRNS
),

[3] = LAYOUT_ergodox_pretty(
KC_TRNS, KC_NO,   KC_NO,   KC_NO,   KC_NO,   KC_NO, MS_BTN3,      MS_BTN3, KC_NO  , KC_NO  , KC_NO  , KC_NO  , KC_NO, KC_NO,
  KC_NO, KC_NO,   KC_NO,   MS_UP,   KC_NO,   KC_NO, MS_BTN1,      MS_BTN1, KC_NO  , KC_NO  , MS_UP  , KC_NO  , KC_NO, KC_NO,
  KC_NO, KC_NO, MS_LEFT, MS_DOWN, MS_RGHT,   KC_NO,                        KC_NO  , MS_LEFT, MS_DOWN, MS_RGHT, KC_NO, KC_NO,
  KC_NO, KC_NO,   KC_NO,   KC_NO,   KC_NO,   KC_NO, MS_BTN2,      MS_BTN2, KC_NO  , KC_NO  , KC_NO  , KC_NO  , KC_NO, KC_NO,
  KC_NO, KC_NO,   KC_NO,   KC_NO,   KC_NO,                                          MS_ACL0, MS_ACL1, MS_ACL2, KC_NO, KC_NO,

                                           KC_TRNS, KC_TRNS,      KC_TRNS, KC_TRNS,
                                                    KC_TRNS,      KC_TRNS,
                                  KC_TRNS, KC_TRNS, KC_TRNS,      KC_TRNS, KC_TRNS, KC_TRNS
)
};




#ifdef OTHER_KEYMAP_C
#    include OTHER_KEYMAP_C
#endif // OTHER_KEYMAP_C

